<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="ado.home" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <center>
                <h1>Insert to Database:</h1>
            </center>
            <hr />
            <br />
            <asp:Label ID="LabelCustomerId" runat="server" Text="Customer Id: "></asp:Label>
            <asp:TextBox ID="TextBoxCustomerId" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelCompanyName" runat="server" Text="Company Name: "></asp:Label>
            <asp:TextBox ID="TextBoxCompanyName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelContactName" runat="server" Text="Contact Name: "></asp:Label>
            <asp:TextBox ID="TextBoxContactName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelContactTitle" runat="server" Text="Contact Title: "></asp:Label>
            <asp:TextBox ID="TextBoxContactTitle" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelAddress" runat="server" Text="Address: "></asp:Label>
            <asp:TextBox ID="TextBoxAddress" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelCity" runat="server" Text="City: "></asp:Label>
            <asp:TextBox ID="TextBoxCity" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelRegion" runat="server" Text="Region: "></asp:Label>
            <asp:TextBox ID="TextBoxRegion" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelPostalCode" runat="server" Text="Postal Code: "></asp:Label>
            <asp:TextBox ID="TextBoxPostalCode" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelCountry" runat="server" Text="Country: "></asp:Label>
            <asp:TextBox ID="TextBoxCountry" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelPhone" runat="server" Text="Phone: "></asp:Label>
            <asp:TextBox ID="TextBoxPhone" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="LabelFax" runat="server" Text="Fax: "></asp:Label>
            <asp:TextBox ID="TextBoxFax" runat="server"></asp:TextBox>
            <br />
            <asp:Button ID="Button2" runat="server" Text="Insert" OnClick="Button2_Click" />
        </div>
        <div>
            <center>
                <h1>Filter/Search:</h1>
            </center>
            <hr />
            <br />
            <asp:DropDownList ID="DropDownList1" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" AutoPostBack="True">
            </asp:DropDownList>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <asp:Button ID="Button1" runat="server" Text="Search" OnClick="Button1_Click" />
        </div>
        <div>
            <center>
                <h1>View, Edit and Delete:</h1>
            </center>
            <hr />
            <br />
            <asp:GridView ID="GridView1" runat="server" CellPadding="3" ForeColor="Black" GridLines="Vertical" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px"
                OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit"
                OnRowDeleting="GridView1_RowDeleting" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        </div>

    </form>
</body>
</html>
